### ISSUE TITLE
Interested in this dataset.

### ISSUE THREAD

**Issue by tim901231** [sunzhihaoict/GRE#1]
Dear author,

I am a student researcher interested in this dataset. Could you please let me know when the Google Form link will be open?

**Comment by sunzhihaoict** [comment]
Thank you for your attention. The Google Form for requesting the dataset has been updated.

**Comment by tim901231** [comment]
Thank you so much.

**Comment by zdaiot** [comment]
@tim901231 您好，请问可以发一下数据链接么？我直接提交google表单，没有人回复。感谢。zdaiot@163.com

**Comment by tim901231** [comment]
> [@tim901231](https://github.com/tim901231) 您好，请问可以发一下数据链接么？我直接提交google表单，没有人回复。感谢。[zdaiot@163.com](mailto:zdaiot@163.com)

Hi @zdaiot 當時research的codebase我有點找不太到了，我之前學校的email信箱也被刪掉了。我後來做的研究方向是focus在人臉deepfake上，用的是DF40這個dataset。
