### ISSUE TITLE
Could you kindly provide me with the necessary permissions on how to download the dataset?

### ISSUE THREAD

**Issue by suncore946** [sunzhihaoict/GRE#6]
Dear GRE author,

I hope this message finds you well. 

You've done an excellent job with generative AI datasets. I am a postgraduate student at Shenzhen University and writing to inquire about obtaining access to the GRE dataset. I have already filled out the necessary form. Could you please provide me with the download permissions or any further instructions?

Thank you for your assistance.
Best regards.

**Comment by zdaiot** [comment]
@suncore946 您好，请问可以发一下数据链接么？我直接提交google表单，没有人回复。感谢。zdaiot@163.com

**Comment by suncore946** [comment]
好像是因为版权问题, 作者不开放下载了, 你可以发起一个issue看看
